interface Iequipments {
  name: string;
  primary: boolean;
  secondary: boolean;
  findGhost: boolean;
  findEvidence: boolean;
  test: boolean;
}

export const equipments: Iequipments[] = [
  {
    name: "Video Camera",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: false,
  },
  {
    name: "D.O.T.S Projector",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: true,
  },
  {
    name: "EMF Reader",
    primary: true,
    secondary: false,
    findGhost: true,
    findEvidence: false,
    test: false,
  },
  {
    name: "Flashlight",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
  {
    name: "Ghost Writing Book",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: false,
  },
  {
    name: "Spirit Box",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: true,
  },
  {
    name: "UV Light",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: true,
  },
  {
    name: "Photo Camera",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Candle",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Crucifix",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Glowstick",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: true,
    test: true,
  },
  {
    name: "Head Mounted Camera",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
  {
    name: "Lighter",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
  {
    name: "Motion Sensor",
    primary: false,
    secondary: true,
    findGhost: true,
    findEvidence: false,
    test: false,
  },
  {
    name: "Parabolic Microphone",
    primary: false,
    secondary: true,
    findGhost: true,
    findEvidence: false,
    test: true,
  },
  {
    name: "Salt",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Sanity Pills",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Smudge Sticks",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Sound Sensor",
    primary: false,
    secondary: true,
    findGhost: true,
    findEvidence: false,
    test: false,
  },
  {
    name: "Strong Flashlight",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
  {
    name: "Thermometer",
    primary: false,
    secondary: true,
    findGhost: true,
    findEvidence: true,
    test: false,
  },
  {
    name: "Tripod",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
];

export const equipmentsBr: Iequipments[] = [
  {
    name: "Câmera de Vídeo",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: false,
  },
  {
    name: "Projetor D.O.T.S",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: true,
  },
  {
    name: "Leitor de EMF",
    primary: true,
    secondary: false,
    findGhost: true,
    findEvidence: true,
    test: false,
  },
  {
    name: "Lanterna",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
  {
    name: "Livro de Escrita Fantasma",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: false,
  },
  {
    name: "Spirit Box",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: true,
  },
  {
    name: "Ultravioleta",
    primary: true,
    secondary: false,
    findGhost: false,
    findEvidence: true,
    test: true,
  },
  {
    name: "Câmera de Foto",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Vela",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Crucifixo",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Câmera de Cabeça",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
  {
    name: "Isqueiro",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
  {
    name: "Sensor de Movimento",
    primary: false,
    secondary: true,
    findGhost: true,
    findEvidence: false,
    test: false,
  },
  {
    name: "Microfone Direcional",
    primary: false,
    secondary: true,
    findGhost: true,
    findEvidence: false,
    test: true,
  },
  {
    name: "Sal",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Remédio de Sanidade",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Incenso",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: true,
  },
  {
    name: "Sensor de Som",
    primary: false,
    secondary: true,
    findGhost: true,
    findEvidence: false,
    test: false,
  },
  {
    name: "Lanterna Forte",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
  {
    name: "Termômetro",
    primary: false,
    secondary: true,
    findGhost: true,
    findEvidence: true,
    test: false,
  },
  {
    name: "Tripé",
    primary: false,
    secondary: true,
    findGhost: false,
    findEvidence: false,
    test: false,
  },
];
