interface Iequipments {
	name: string;
	primary: boolean;
	secondary: boolean;
	findGhost: boolean;
	findEvidence: boolean;
	test: boolean;
}

export const equipments: Iequipments[] = [
	{
		name: 'Video Camera',
		primary: true,
		secondary: false,
		findGhost: false,
		findEvidence: true,
		test: false,
	},
	{
		name: 'D.O.T.S Projector',
		primary: true,
		secondary: false,
		findGhost: false,
		findEvidence: true,
		test: true,
	},
	{
		name: 'EMF Reader',
		primary: true,
		secondary: false,
		findGhost: true,
		findEvidence: false,
		test: false,
	},
	{
		name: 'Flashlight',
		primary: true,
		secondary: false,
		findGhost: false,
		findEvidence: false,
		test: false,
	},
	{
		name: 'Ghost Writing Book',
		primary: true,
		secondary: false,
		findGhost: false,
		findEvidence: true,
		test: false,
	},
	{
		name: 'Spirit Box',
		primary: true,
		secondary: false,
		findGhost: false,
		findEvidence: true,
		test: true,
	},
	{
		name: 'UV Light',
		primary: true,
		secondary: false,
		findGhost: false,
		findEvidence: true,
		test: true,
	},
	{
		name: 'Photo Camera',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: true,
	},
	{
		name: 'Candle',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: true,
	},
	{
		name: 'Crucifix',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: true,
	},
	{
		name: 'Glowstick',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: true,
		test: true,
	},
	{
		name: 'Head Mounted Camera',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: false,
	},
	{
		name: 'Lighter',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: false,
	},
	{
		name: 'Motion Sensor',
		primary: false,
		secondary: true,
		findGhost: true,
		findEvidence: false,
		test: false,
	},
	{
		name: 'Parabolic Microphone',
		primary: false,
		secondary: true,
		findGhost: true,
		findEvidence: false,
		test: true,
	},
	{
		name: 'Salt',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: true,
	},
	{
		name: 'Sanity Pills',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: true,
	},
	{
		name: 'Smudge Sticks',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: true,
	},
	{
		name: 'Sound Sensor',
		primary: false,
		secondary: true,
		findGhost: true,
		findEvidence: false,
		test: false,
	},
	{
		name: 'Strong Flashlight',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: false,
	},
	{
		name: 'Thermometer',
		primary: false,
		secondary: true,
		findGhost: true,
		findEvidence: true,
		test: false,
	},
	{
		name: 'Tripod',
		primary: false,
		secondary: true,
		findGhost: false,
		findEvidence: false,
		test: false,
	},
];
